#version: "3.8"
#
#services:
#  mongo:
#    image: mongo
#    container_name: mongo
#    restart: always
#    ports:
#      - 27017:27017
#    volumes:
#      - mongo:/data
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=ahmed
#      - MONGO_INITDB_ROOT_PASSWORD=ahmed
#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=ahmed
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=ahmed
#      - ME_CONFIG_MONGODB_SERVER=mongo
#
#volumes:
#  mongo: {}

#version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ahmed
      MONGO_INITDB_ROOT_PASSWORD: ahmed
    networks:
      - chatme-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ahmed
      ME_CONFIG_MONGODB_ADMINPASSWORD: ahmed
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      - mongodb
    networks:
      - chatme-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatme-app
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://ahmed:ahmed@mongodb:27017/chatme_app?authSource=admin
    depends_on:
      - mongodb
    networks:
      - chatme-network

networks:
  chatme-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local