services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ahmed
      - MONGO_INITDB_ROOT_PASSWORD=ahmed
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=ahmed
      - ME_CONFIG_MONGODB_ADMINPASSWORD=ahmed
      - ME_CONFIG_MONGODB_SERVER=mongo

volumes:
  mongo: {}