services:
  mongodb:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AhmedMokhtar
      - MONGO_INITDB_ROOT_PASSWORD=Ahmed123

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=AhmedMokhtar
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Ahmed123
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo: {}