spring:
  application:
    name: ChatMe-SpringBoot

  data:
    mongodb:
      uri: mongodb://ahmed:ahmed@mongodb:27017/chatme_app?authSource=admin

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8088