  spring:
    application:
      name: ChatMe-SpringBoot

    data:
      mongodb:
        username: ahmed
        password: ahmed
        host: localhost
        port: 27017
        database: chatme_app
        authentication-database: admin

  server:
    port: 8088